# docker-compose build
version: '2.1'

services:
  python:
    build:
      context: ../../
      dockerfile: ./docker/python/Dockerfile
    container_name: fireguard-python
    image: python

networks:
  default:
    external: true
    name: fireguard-network
