# docker-compose build
version: '3.3'

services:
  gis:
    image: tbd_gis
    build:
      context: .
      target: gis
      dockerfile: .docker/Dockerfile_gis
      tags:
        - tbd_gis:${VERSION}
    volumes:
      - type: bind
        source: ./config
        target: /appl/config
      - data:/appl/data
      - type: bind
        source: ./gis
        target: /appl/gis

  tbd_dev_svc:
    image: tbd_dev_svc
    build:
      context: .
      target: tbd_dev_svc
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        PERF_VERSION: ${PERF_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
        - tbd_dev_svc:${VERSION}
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ./config
        target: /appl/config
      - data:/appl/data
      - type: bind
        source: ./tbd
        target: /appl/tbd
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  tbd_prod_svc:
    image: tbd_prod_svc
    build:
      context: .
      target: tbd_prod_svc
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
        - tbd_prod_svc:${VERSION}
    volumes:
      - data:/appl/data

  firestarr:
    image: firestarr
    build:
      context: .
      target: firestarr
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
        - firestarr:${VERSION}
    volumes:
      - type: bind
        source: ./tbd/settings.ini
        target: /appl/tbd/settings.ini
      - data:/appl/data

volumes:
  data:
    # symlink to your actual directory if you don't want it in the project folder
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
