# docker-compose build
version: '3.3'
volumes:
  dbbackups:
  postgis-data:

services:
  gis:
    build:
      context: .
      dockerfile: .docker/Dockerfile_gis
    image: thinkwhere/gdal-python
    volumes:
      - type: bind
        source: ./settings.ini
        target: /appl/settings.ini
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./gis
        target: /appl/gis
      - type: bind
        source: ./util
        target: /appl/util

  tbd:
    build:
      context: .
      dockerfile: .docker/Dockerfile_tbd
    security_opt:
      - seccomp:unconfined
    image: gcc:10.3
    ports:
      - "2222:22"
    volumes:
      - type: bind
        source: ./settings.ini
        target: /appl/settings.ini
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./data/generated/grid
        target: /appl/100m/default
      - type: bind
        source: ./tbd
        target: /appl/tbd
      - type: bind
        source: ./util
        target: /appl/util
    restart: on-failure
    cap_add:
        - SYS_PTRACE
