# docker-compose build
version: '3.3'

services:
  gis:
    image: tbd_gis
    build:
      context: .
      target: gis
      dockerfile: .docker/Dockerfile_gis
      tags:
      - tbd_gis:${VERSION}
    volumes:
      - type: bind
        source: ./config
        target: /appl/config
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./gis
        target: /appl/gis
      - type: bind
        source: ./util
        target: /appl/util


  tbd_dev_svc:
    image: tbd_dev_svc
    build:
      context: .
      target: tbd_dev_svc
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        PERF_VERSION: ${PERF_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
      - tbd_dev_svc:${VERSION}
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ./config
        target: /appl/config
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./data/generated/grid
        target: /appl/100m/default
      - type: bind
        source: ./tbd
        target: /appl/tbd
      - type: bind
        source: ./util
        target: /appl/util
    restart: on-failure
    cap_add:
        - SYS_PTRACE


  tbd_prod:
    image: tbd_prod
    build:
      context: .
      target: tbd_prod
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
      - tbd_prod:${VERSION}
    volumes:
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./data/generated/grid
        target: /appl/100m/default


  firestarr:
    image: firestarr
    build:
      context: .
      target: firestarr
      dockerfile: .docker/Dockerfile_tbd
      args:
        GCC_VERSION: ${GCC_VERSION}
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
      tags:
      - firestarr:${VERSION}
    volumes:
      - type: bind
        source: ./tbd/settings.ini
        target: /appl/tbd/settings.ini
      - type: bind
        source: ./data
        target: /appl/data
      - type: bind
        source: ./data/generated/grid
        target: /appl/100m/default

