name: Docker Compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make data directory
        run: mkdir data
      - name: Build the stack
        run: docker-compose up -d
