name: Doxygen Action

on:
  push:
    branches: [ main ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: "documentation/doxygen.conf"
        working-directory: "."
        additional-packages: |
          graphviz
          ttf-freefont

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/build/html
